-- === ARCHIVO GENERADO -- NO EDITAR ===
-- Extraido de: 2 lead_loader  (workflow id f5383ae7-dd2e-4177-9875-c6dcff27e3d5)
-- Nodo:        db_upsert_lead_state
--
-- La fuente de verdad es el JSON del workflow en workflows/exports/.
-- Regenerar con: node scripts/extract_workflow_code.js
-- =====================================

insert into lead_state (
  lead_id,
  organization_id,
  agent_id,
  stage,
  intent_last,
  interest_score,
  service_interest,
  vehicle_type,
  district,
  mentioned_vehicle_type,
  confirmed_vehicle_type,
  mentioned_district,
  confirmed_district,
  missing_fields,
  last_bot_action,
  next_goal,
  human_handoff,
  booking_options,
  booking_date,
  booking_time,
  slot_id,
  availability_confirmed,
  availability_window,
  availability_label,
  calendar_id,
  duration_minutes,
  days_ahead,
  start_offset_days,
  max_slots,
  service_address,
  address_reference,
  address_confirmed,
  address_confirmed_at,
  cancellation_reason,
  reschedule_reason,
  last_appointment_event_id,
  staff_id,
  staff_name,
  address_collection_attempts,
  payment_preference,
  payment_status,
  flow_order_id,
  flow_payment_url,
  payment_mode,
  quoted_price,
  updated_at
)
values (
  '{{ $node["db_upsert_lead"].json["id"] }}'::uuid,
  nullif('{{ String($node["code_prepare_lookup"].json["lookup"]?.organization_id || "").replace(/'/g, "''") }}', '')::uuid,
  nullif('{{ String($node["code_prepare_lookup"].json["lookup"]?.agent_id || "").replace(/'/g, "''") }}', '')::uuid,
  'new_lead',
  null,
  0,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  '[]'::jsonb,
  'none',
  'identify_intent',
  false,
  '[]'::jsonb,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  120,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  null,
  null,
  null,
  null,
  null,
  0,
  null,
  null,
  null,
  null,
  null,
  null,
  now()
)
on conflict (lead_id)
do update set
  organization_id = coalesce(excluded.organization_id, lead_state.organization_id),
  agent_id = coalesce(excluded.agent_id, lead_state.agent_id),
  updated_at = lead_state.updated_at
returning
  lead_id,
  organization_id,
  agent_id,
  stage,
  intent_last,
  interest_score,
  service_interest,
  vehicle_type,
  district,
  mentioned_vehicle_type,
  confirmed_vehicle_type,
  mentioned_district,
  confirmed_district,
  missing_fields,
  last_bot_action,
  next_goal,
  human_handoff,
  booking_options,
  booking_date,
  booking_time,
  slot_id,
  availability_confirmed,
  availability_window,
  availability_label,
  calendar_id,
  duration_minutes,
  days_ahead,
  start_offset_days,
  max_slots,
  service_address,
  address_reference,
  address_confirmed,
  address_confirmed_at,
  cancellation_reason,
  reschedule_reason,
  last_appointment_event_id,
  staff_id,
  staff_name,
  address_collection_attempts,
  payment_preference,
  payment_status,
  flow_order_id,
  flow_payment_url,
  payment_mode,
  quoted_price,
  updated_at;
