INSERT INTO public.qa_test_scenarios_temp
  (scenario_key, name, suite, enabled, priority, tags, steps, expected_outcome, category)
VALUES
  ('5699033001', 'BASE 08: agenda -> consultar reserva -> reagendar -> cancelar (encadenado)', 'closer_base_flows', true, 15, ARRAY['base','decision_tree','cancel','reschedule','existing_appointment']::text[], '[{"role":"user","text":"Hola, quiero el lavado premium","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["ask_missing_data"]}},{"role":"user","text":"Vivo en Las Condes, tengo un SUV","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["send_quote"]}},{"role":"user","text":"Dale, quiero agendar","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["offer_available_slots"]}},{"role":"user","text":"El jueves a las 15:00","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["collect_address","offer_available_slots","answer_question"]}},{"role":"user","text":"Mi direccion es Av. Apoquindo 4500","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["confirm_address","confirm_booking"]}},{"role":"user","text":"Si, confirmo la reserva","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["confirm_booking","offer_available_slots","confirm_address"]}},{"role":"user","text":"Tengo alguna reserva agendada?","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["answer_question"]}},{"role":"user","text":"Necesito cambiar mi hora, puede ser el viernes?","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["reschedule_booking"]}},{"role":"user","text":"Quiero cancelar mi reserva mejor","source_metadata":{"provider":"meta_whatsapp_cloud_api","phone_number_id":"qa-phone-ahumada-agent-aware"},"expect":{"must_have_audit":true,"decision_action_any":["cancel_booking"]}}]'::jsonb, 'El bot debe completar una reserva de punta a punta, luego confirmar que el lead tiene una reserva activa cuando pregunta, luego iniciar el proceso de reagendarla cuando lo pide, y finalmente cancelarla cuando lo pide. Nota: pasos que tocan Google Calendar de verdad pueden fallar en el detalle del evento -- lo que importa es que rules_engine rutee a la accion correcta en cada paso.', 'base')
ON CONFLICT (scenario_key) DO UPDATE SET
  name = EXCLUDED.name,
  suite = EXCLUDED.suite,
  priority = EXCLUDED.priority,
  tags = EXCLUDED.tags,
  steps = EXCLUDED.steps,
  expected_outcome = EXCLUDED.expected_outcome,
  category = EXCLUDED.category,
  updated_at = now();
